import { mkdir, readFile, rm, writeFile, copyFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const root = path.resolve(path.dirname(__filename), "..");
const dist = path.join(root, "dist");
const esmDir = path.join(dist, "esm");
const wasmRootDir = path.join(root, "wasm");
const wasmDistDir = path.join(dist, "wasm");
const sourceFiles = ["geometry.js", "reed-solomon.js", "security.js", "vision.js", "quadqr.js", "wasm.js", "benchmark.js"];

function fail(message) {
  console.error(message);
  process.exit(1);
}

async function ensureDir(dir) {
  await mkdir(dir, { recursive: true });
}

function compileWasm() {
  const source = path.join(root, "wasm-src", "quadqr_core.c");
  const output = path.join(wasmRootDir, "quadqr-core.wasm");
  const args = [
    "--target=wasm32",
    "-Oz",
    "-nostdlib",
    "-Wl,--no-entry",
    "-Wl,--export=crc32_bytes",
    "-Wl,--export=__heap_base",
    "-Wl,--export-memory",
    "-Wl,--stack-first",
    "-Wl,-z,stack-size=32768",
    "-Wl,--initial-memory=131072",
    "-Wl,--max-memory=16777216",
    "-o",
    output,
    source
  ];
  const result = spawnSync("clang", args, { encoding: "utf8" });
  if (result.status !== 0) {
    if (existsSync(output)) {
      console.warn("QuadQR build: clang unavailable or WASM compilation failed; using the checked-in prebuilt wasm/quadqr-core.wasm asset.");
      return;
    }
    fail(`Unable to compile QuadQR WASM and no prebuilt asset is available. Install clang or restore wasm/quadqr-core.wasm.\n${result.stderr || result.stdout || result.error?.message || ""}`);
  }
}

function parseImports(source) {
  const imports = [];
  const withoutImports = source.replace(/import\s*\{([\s\S]*?)\}\s*from\s*["']([^"']+)["'];?\s*/g, (_, names, specifier) => {
    const bindings = names.split(",").map((value) => value.trim()).filter(Boolean).map((binding) => {
      const match = binding.match(/^(\w+)\s+as\s+(\w+)$/);
      return match ? { imported: match[1], local: match[2] } : { imported: binding, local: binding };
    });
    imports.push({ specifier, bindings });
    return "";
  });
  return { source: withoutImports, imports };
}

function transformModule(source) {
  const { source: noImports, imports } = parseImports(source);
  const exports = new Set();

  let code = noImports.replace(/export\s+(async\s+)?function\s+(\w+)/g, (_, asyncPart = "", name) => {
    exports.add(name);
    return `${asyncPart || ""}function ${name}`;
  });

  code = code.replace(/export\s+(const|let|var|class)\s+(\w+)/g, (_, kind, name) => {
    exports.add(name);
    return `${kind} ${name}`;
  });

  code = code.replace(/export\s*\{([\s\S]*?)\};?/g, (_, names) => {
    for (const raw of names.split(",")) {
      const item = raw.trim();
      if (!item) continue;
      const match = item.match(/^(\w+)\s+as\s+(\w+)$/);
      exports.add(match ? match[2] : item);
    }
    return "";
  });

  return { code, imports, exports: [...exports] };
}

function stripBlockComments(source) {
  let out = "";
  let i = 0;
  let quote = null;
  let templateDepth = 0;
  while (i < source.length) {
    const ch = source[i];
    const next = source[i + 1];

    if (quote) {
      out += ch;
      if (ch === "\\") {
        if (i + 1 < source.length) out += source[++i];
      } else if (ch === quote) {
        quote = null;
      }
      i++;
      continue;
    }

    if (templateDepth > 0) {
      out += ch;
      if (ch === "\\") {
        if (i + 1 < source.length) out += source[++i];
      } else if (ch === "`") {
        templateDepth = 0;
      }
      i++;
      continue;
    }

    if (ch === "'" || ch === '"') {
      quote = ch;
      out += ch;
      i++;
      continue;
    }
    if (ch === "`") {
      templateDepth = 1;
      out += ch;
      i++;
      continue;
    }

    if (ch === "/" && next === "*") {
      const end = source.indexOf("*/", i + 2);
      if (end === -1) break;
      i = end + 2;
      continue;
    }

    out += ch;
    i++;
  }
  return out;
}

function compactBundle(source) {
  return stripBlockComments(source)
    .split("\n")
    .map((line) => line.trimEnd())
    .filter((line, index, lines) => line.trim() || (index > 0 && lines[index - 1].trim()))
    .join("\n")
    .replace(/\n{3,}/g, "\n\n");
}

async function buildGlobalBundle() {
  const moduleOrder = ["geometry.js", "reed-solomon.js", "security.js", "vision.js", "quadqr.js"];
  const moduleVar = new Map(moduleOrder.map((file) => [file, `__qqr_${file.replace(/\W+/g, "_")}`]));
  const pieces = [
    "/* QuadQR browser global build. Generated by npm run build. */",
    "(function (global) {",
    '"use strict";',
    "const __qqrScriptSrc = typeof document !== 'undefined' ? document.currentScript?.src || null : null;"
  ];

  for (const file of moduleOrder) {
    const raw = await readFile(path.join(root, "library", file), "utf8");
    const transformed = transformModule(raw);
    const injections = [];
    for (const dependency of transformed.imports) {
      const depName = path.basename(dependency.specifier);
      const depVar = moduleVar.get(depName);
      if (!depVar) fail(`Global build does not know dependency ${dependency.specifier} from ${file}.`);
      const bindings = dependency.bindings.map(({ imported, local }) => imported === local ? imported : `${imported}: ${local}`).join(", ");
      injections.push(`const { ${bindings} } = ${depVar};`);
    }

    const returned = transformed.exports.join(", ");
    pieces.push(
      `const ${moduleVar.get(file)} = (function () {`,
      ...injections,
      transformed.code,
      `return { ${returned} };`,
      "})();"
    );
  }

  const quadVar = moduleVar.get("quadqr.js");
  pieces.push(`const QuadQR = ${quadVar};`);
  pieces.push(`
QuadQR.initWasm = async function initWasm(options = {}) {
  const url = options.url
    ? new URL(options.url, __qqrScriptSrc || (typeof location !== "undefined" ? location.href : undefined))
    : (__qqrScriptSrc
      ? new URL("./wasm/quadqr-core.wasm", __qqrScriptSrc)
      : new URL("./wasm/quadqr-core.wasm", location.href));
  const response = options.bytes ? null : await fetch(url);
  if (response && !response.ok) throw new Error("Unable to load QuadQR WASM (" + response.status + ").");
  const bytes = options.bytes instanceof Uint8Array
    ? options.bytes
    : options.bytes
      ? new Uint8Array(options.bytes)
      : new Uint8Array(await response.arrayBuffer());
  const result = await WebAssembly.instantiate(bytes, {});
  const instance = result.instance;
  const memory = instance.exports.memory;
  const crc32Bytes = instance.exports.crc32_bytes;
  const heapExport = instance.exports.__heap_base;
  const heapBase = Number((heapExport && heapExport.value) || heapExport || 65536);
  if (!(memory instanceof WebAssembly.Memory) || typeof crc32Bytes !== "function") {
    throw new Error("QuadQR WASM exports are invalid.");
  }
  QuadQR.installCrc32Accelerator(function (input) {
    const data = input instanceof Uint8Array ? input : new Uint8Array(input);
    const required = heapBase + data.length;
    if (required > memory.buffer.byteLength) memory.grow(Math.ceil((required - memory.buffer.byteLength) / 65536));
    new Uint8Array(memory.buffer, heapBase, data.length).set(data);
    return crc32Bytes(heapBase, data.length) >>> 0;
  });
  return Object.freeze({ enabled: true, module: "quadqr-core", accelerators: Object.freeze(["crc32"]), bytes: bytes.length });
};`);
  pieces.push(
    "global.QuadQR = QuadQR;",
    "})(typeof globalThis !== 'undefined' ? globalThis : typeof window !== 'undefined' ? window : this);",
    ""
  );

  const bundle = pieces.join("\n");
  await writeFile(path.join(dist, "quadqr.js"), bundle);
  await writeFile(path.join(dist, "quadqr.min.js"), compactBundle(bundle));
}

async function build() {
  await rm(dist, { recursive: true, force: true });
  await ensureDir(esmDir);
  await ensureDir(wasmRootDir);
  await ensureDir(wasmDistDir);

  compileWasm();
  await copyFile(path.join(wasmRootDir, "quadqr-core.wasm"), path.join(wasmDistDir, "quadqr-core.wasm"));

  for (const file of sourceFiles) {
    await copyFile(path.join(root, "library", file), path.join(esmDir, file));
  }
  await copyFile(path.join(root, "library", "node.js"), path.join(esmDir, "node.js"));

  await writeFile(path.join(dist, "index.js"), [
    'export * from "./esm/quadqr.js";',
    'export { initWasm, getWasmState, disableWasm } from "./esm/wasm.js";',
    ""
  ].join("\n"));

  await writeFile(path.join(dist, "browser.js"), [
    'export * from "./esm/quadqr.js";',
    'export { initWasm, getWasmState, disableWasm } from "./esm/wasm.js";',
    ""
  ].join("\n"));

  await writeFile(path.join(dist, "node.js"), [
    'export * from "./esm/node.js";',
    ""
  ].join("\n"));

  await writeFile(path.join(dist, "benchmark.js"), [
    'export * from "./esm/benchmark.js";',
    ""
  ].join("\n"));

  // Modern Node (>=20.19) can synchronously require ESM without top-level await.
  // These tiny wrappers provide familiar CommonJS entry files without maintaining
  // a second codec implementation.
  await writeFile(path.join(dist, "index.cjs"), 'module.exports = require("./index.js");\n');
  await writeFile(path.join(dist, "node.cjs"), 'module.exports = require("./node.js");\n');
  await writeFile(path.join(dist, "benchmark.cjs"), 'module.exports = require("./benchmark.js");\n');

  await buildGlobalBundle();

  console.log("QuadQR build complete:");
  console.log("  dist/index.js       ESM/core");
  console.log("  dist/index.cjs      CommonJS wrapper (Node >=20.19)");
  console.log("  dist/node.js        Node PNG/file helpers");
  console.log("  dist/browser.js     Browser ESM");
  console.log("  dist/quadqr.min.js  CDN/global build");
  console.log("  dist/wasm/*         Prebuilt optional WASM accelerator");
}

build().catch((error) => fail(error.stack || error.message));
