import { mkdir, readFile, rm, writeFile, copyFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { ensureWasmBuild } from "./wasm-build.js";

const __filename = fileURLToPath(import.meta.url);
const root = path.resolve(path.dirname(__filename), "..");
const dist = path.join(root, "dist");
const esmDir = path.join(dist, "esm");
const wasmRootDir = path.join(root, "wasm");
const wasmDistDir = path.join(dist, "wasm");
const sourceFiles = ["geometry.js", "reed-solomon.js", "security.js", "vision.js", "deflate.js", "brotli.js", "quadqr.js", "wasm.js", "benchmark.js", "camera-scanner-worker.js"];

function fail(message) {
  console.error(message);
  process.exit(1);
}

async function ensureDir(dir) {
  await mkdir(dir, { recursive: true });
}

function parseImports(source) {
  const imports = [];
  const withoutImports = source.replace(/import\s*\{([\s\S]*?)\}\s*from\s*["']([^"']+)["'];?\s*/g, (_, names, specifier) => {
    const bindings = names.split(",").map((value) => value.trim()).filter(Boolean).map((binding) => {
      const match = binding.match(/^(\w+)\s+as\s+(\w+)$/);
      return match ? { imported: match[1], local: match[2] } : { imported: binding, local: binding };
    });
    imports.push({ specifier, bindings });
    return "";
  });
  return { source: withoutImports, imports };
}

function transformModule(source) {
  const { source: noImports, imports } = parseImports(source);
  const exports = new Set();

  let code = noImports.replace(/export\s+(async\s+)?function\s+(\w+)/g, (_, asyncPart = "", name) => {
    exports.add(name);
    return `${asyncPart || ""}function ${name}`;
  });

  code = code.replace(/export\s+(const|let|var|class)\s+(\w+)/g, (_, kind, name) => {
    exports.add(name);
    return `${kind} ${name}`;
  });

  code = code.replace(/export\s*\{([\s\S]*?)\};?/g, (_, names) => {
    for (const raw of names.split(",")) {
      const item = raw.trim();
      if (!item) continue;
      const match = item.match(/^(\w+)\s+as\s+(\w+)$/);
      exports.add(match ? match[2] : item);
    }
    return "";
  });

  return { code, imports, exports: [...exports] };
}

function stripBlockComments(source) {
  let out = "";
  let i = 0;
  let quote = null;
  let templateDepth = 0;
  while (i < source.length) {
    const ch = source[i];
    const next = source[i + 1];

    if (quote) {
      out += ch;
      if (ch === "\\") {
        if (i + 1 < source.length) out += source[++i];
      } else if (ch === quote) {
        quote = null;
      }
      i++;
      continue;
    }

    if (templateDepth > 0) {
      out += ch;
      if (ch === "\\") {
        if (i + 1 < source.length) out += source[++i];
      } else if (ch === "`") {
        templateDepth = 0;
      }
      i++;
      continue;
    }

    if (ch === "'" || ch === '"') {
      quote = ch;
      out += ch;
      i++;
      continue;
    }
    if (ch === "`") {
      templateDepth = 1;
      out += ch;
      i++;
      continue;
    }

    if (ch === "/" && next === "*") {
      const end = source.indexOf("*/", i + 2);
      if (end === -1) break;
      i = end + 2;
      continue;
    }

    out += ch;
    i++;
  }
  return out;
}

function compactBundle(source) {
  return stripBlockComments(source)
    .split("\n")
    .map((line) => line.trimEnd())
    .filter((line, index, lines) => line.trim() || (index > 0 && lines[index - 1].trim()))
    .join("\n")
    .replace(/\n{3,}/g, "\n\n");
}

async function buildGlobalBundle() {
  const moduleOrder = ["geometry.js", "reed-solomon.js", "security.js", "vision.js", "deflate.js", "brotli.js", "quadqr.js"];
  const moduleVar = new Map(moduleOrder.map((file) => [file, `__qqr_${file.replace(/\W+/g, "_")}`]));
  const pieces = [
    "/* QuadQR browser global build. Generated by npm run build. */",
    "(function (global) {",
    '"use strict";',
    "const __qqrScriptSrc = typeof document !== 'undefined' ? document.currentScript?.src || null : null;"
  ];

  for (const file of moduleOrder) {
    const raw = await readFile(path.join(root, "library", file), "utf8");
    const transformed = transformModule(raw);
    // library/quadqr.js uses import.meta.url to locate its module camera worker.
    // The classic CDN/global bundle cannot contain import.meta syntax, so use
    // the current script URL as the equivalent base in that build.
    transformed.code = transformed.code.replace(
      /\bimport\.meta\.url\b/g,
      "(__qqrScriptSrc || (typeof location !== 'undefined' ? location.href : ''))"
    );
    const injections = [];
    for (const dependency of transformed.imports) {
      const depName = path.basename(dependency.specifier);
      const depVar = moduleVar.get(depName);
      if (!depVar) fail(`Global build does not know dependency ${dependency.specifier} from ${file}.`);
      const bindings = dependency.bindings.map(({ imported, local }) => imported === local ? imported : `${imported}: ${local}`).join(", ");
      injections.push(`const { ${bindings} } = ${depVar};`);
    }

    const returned = transformed.exports.join(", ");
    pieces.push(
      `const ${moduleVar.get(file)} = (function () {`,
      ...injections,
      transformed.code,
      `return { ${returned} };`,
      "})();"
    );
  }

  const quadVar = moduleVar.get("quadqr.js");
  pieces.push(`const QuadQR = ${quadVar};`);
  pieces.push(`
QuadQR.initWasm = async function initWasm(options = {}) {
  const url = options.url
    ? new URL(options.url, __qqrScriptSrc || (typeof location !== "undefined" ? location.href : undefined))
    : (__qqrScriptSrc
      ? new URL("./wasm/quadqr-core.wasm", __qqrScriptSrc)
      : new URL("./wasm/quadqr-core.wasm", location.href));
  const response = options.bytes ? null : await fetch(url);
  if (response && !response.ok) throw new Error("Unable to load QuadQR WASM (" + response.status + ").");
  const bytes = options.bytes instanceof Uint8Array
    ? options.bytes
    : options.bytes
      ? new Uint8Array(options.bytes)
      : new Uint8Array(await response.arrayBuffer());
  const result = await WebAssembly.instantiate(bytes, {});
  const instance = result.instance;
  const memory = instance.exports.memory;
  const crc32Bytes = instance.exports.crc32_bytes;
  const buildBinaryRgba = instance.exports.build_binary_rgba;
  const heapExport = instance.exports.__heap_base;
  const heapBase = Number((heapExport && heapExport.value) || heapExport || 65536);
  if (!(memory instanceof WebAssembly.Memory) || typeof crc32Bytes !== "function") {
    throw new Error("QuadQR WASM exports are invalid.");
  }
  const ensureMemory = function (required) {
    if (required > memory.buffer.byteLength) memory.grow(Math.ceil((required - memory.buffer.byteLength) / 65536));
  };
  QuadQR.installCrc32Accelerator(function (input) {
    const data = input instanceof Uint8Array
      ? input
      : ArrayBuffer.isView(input)
        ? new Uint8Array(input.buffer, input.byteOffset, input.byteLength)
        : new Uint8Array(input);
    const required = heapBase + data.length;
    ensureMemory(required);
    new Uint8Array(memory.buffer, heapBase, data.length).set(data);
    return crc32Bytes(heapBase, data.length) >>> 0;
  });
  const accelerators = ["crc32"];
  if (typeof buildBinaryRgba === "function") {
    const align16 = function (value) { return (value + 15) & ~15; };
    __qqr_vision_js.installVisionAccelerator({
      buildBinary: function (imageData, scanOptions = {}) {
        const width = Number(imageData && imageData.width) || 0;
        const height = Number(imageData && imageData.height) || 0;
        const pixels = width * height;
        if (!pixels || !imageData || !imageData.data || imageData.data.length < pixels * 4) {
          throw new Error("Valid ImageData is required for WASM preprocessing.");
        }
        const raw = imageData.data;
        const rgba = raw instanceof Uint8Array
          ? raw
          : new Uint8Array(raw.buffer, raw.byteOffset, raw.byteLength);
        const rgbaBytes = pixels * 4;
        const inputPtr = align16(heapBase);
        const grayPtr = align16(inputPtr + rgbaBytes);
        const binaryPtr = align16(grayPtr + pixels);
        ensureMemory(binaryPtr + pixels);
        new Uint8Array(memory.buffer, inputPtr, rgbaBytes).set(rgba.subarray(0, rgbaBytes));
        const mode = scanOptions.grayMode === "value" ? 0 : 1;
        const offset = Math.round(Number(scanOptions.thresholdOffset) || 0);
        const packed = buildBinaryRgba(inputPtr, pixels, mode, offset, grayPtr, binaryPtr) >>> 0;
        const gray = new Uint8Array(pixels);
        const binary = new Uint8Array(pixels);
        gray.set(new Uint8Array(memory.buffer, grayPtr, pixels));
        binary.set(new Uint8Array(memory.buffer, binaryPtr, pixels));
        return {
          gray: gray,
          binary: binary,
          threshold: packed & 255,
          baseThreshold: (packed >>> 8) & 255,
          grayMode: scanOptions.grayMode || "luminance",
          accelerated: "wasm"
        };
      }
    });
    accelerators.push("scanner-preprocess");
  }
  return Object.freeze({ enabled: true, module: "quadqr-core", accelerators: Object.freeze(accelerators), bytes: bytes.length });
};`);
  pieces.push(
    "global.QuadQR = QuadQR;",
    "})(typeof globalThis !== 'undefined' ? globalThis : typeof window !== 'undefined' ? window : this);",
    ""
  );

  const bundle = pieces.join("\n");
  await writeFile(path.join(dist, "quadqr.js"), bundle);
  await writeFile(path.join(dist, "quadqr.min.js"), compactBundle(bundle));
}

async function build() {
  // Verify/rebuild WASM before touching dist so a stale-WASM failure never
  // deletes an otherwise usable existing distribution.
  await ensureWasmBuild();

  await rm(dist, { recursive: true, force: true });
  await ensureDir(esmDir);
  await ensureDir(wasmRootDir);
  await ensureDir(wasmDistDir);

  await copyFile(path.join(wasmRootDir, "quadqr-core.wasm"), path.join(wasmDistDir, "quadqr-core.wasm"));

  for (const file of sourceFiles) {
    await copyFile(path.join(root, "library", file), path.join(esmDir, file));
  }
  await copyFile(path.join(root, "library", "node.js"), path.join(esmDir, "node.js"));

  // The ESM scanner resolves the worker beside dist/esm/quadqr.js. The classic
  // CDN/global build resolves it beside dist/quadqr(.min).js, so generate a
  // second tiny worker entry whose imports point into dist/esm.
  const cameraWorkerSource = await readFile(path.join(root, "library", "camera-scanner-worker.js"), "utf8");
  const globalCameraWorkerSource = cameraWorkerSource
    .replace('from "./quadqr.js"', 'from "./esm/quadqr.js"')
    .replace('from "./vision.js"', 'from "./esm/vision.js"')
    .replace('from "./wasm.js"', 'from "./esm/wasm.js"');
  await writeFile(path.join(dist, "camera-scanner-worker.js"), globalCameraWorkerSource);

  await writeFile(path.join(dist, "index.js"), [
    'export * from "./esm/quadqr.js";',
    'export { initWasm, getWasmState, disableWasm } from "./esm/wasm.js";',
    ""
  ].join("\n"));

  await writeFile(path.join(dist, "browser.js"), [
    'export * from "./esm/quadqr.js";',
    'export { initWasm, getWasmState, disableWasm } from "./esm/wasm.js";',
    ""
  ].join("\n"));

  await writeFile(path.join(dist, "node.js"), [
    'export * from "./esm/node.js";',
    ""
  ].join("\n"));

  await writeFile(path.join(dist, "benchmark.js"), [
    'export * from "./esm/benchmark.js";',
    ""
  ].join("\n"));

  // Modern Node (>=20.19) can synchronously require ESM without top-level await.
  // These tiny wrappers provide familiar CommonJS entry files without maintaining
  // a second codec implementation.
  await writeFile(path.join(dist, "index.cjs"), 'module.exports = require("./index.js");\n');
  await writeFile(path.join(dist, "node.cjs"), 'module.exports = require("./node.js");\n');
  await writeFile(path.join(dist, "benchmark.cjs"), 'module.exports = require("./benchmark.js");\n');

  await buildGlobalBundle();

  console.log("QuadQR build complete:");
  console.log("  dist/index.js       ESM/core");
  console.log("  dist/index.cjs      CommonJS wrapper (Node >=20.19)");
  console.log("  dist/node.js        Node PNG/file helpers");
  console.log("  dist/browser.js     Browser ESM");
  console.log("  dist/quadqr.min.js  CDN/global build");
  console.log("  dist/camera-scanner-worker.js  Camera module worker");
  console.log("  dist/wasm/*         Prebuilt optional WASM accelerator");
}

build().catch((error) => fail(error.stack || error.message));
